version: "3.9"
services:
  fileio:
    container_name: "persistence-service"
    build:
      context: ./FileIO
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    stdin_open: true
    tty: true
  uno:
    container_name: "cah-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fileio
    environment:
      - DISPLAY=host.docker.internal:0
      - PERSISTENCEHTTPSERVER=persistence-service:8084