version: "3.9"
services:
  sqldb:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CAH
      MYSQL_DATABASE: cah
      MYSQL_USER: cah
      MYSQL_PASSWORD: cah
    volumes:
      - .:/var/lib/sql/cah
  persistence:
    container_name: "persistence-service"
    build:
      context: ./Persistence
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    environment:
      - DATABASE_HOST=sqldb:3306
      - MYSQL_USER=cah
      - MYSQL_PASSWORD=cah
    stdin_open: true
    tty: true





#  fileio:
#    container_name: "fileio-service"
#    build:
#      context: Persistence
#      dockerfile: ./Dockerfile
#    ports:
#      - "8084:8084"
#    stdin_open: true
#    tty: true




  cah:
    container_name: "cah-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - fileio
    environment:
      - DISPLAY=host.docker.internal:0
      - FILEIOHTTPSERVER=fileio-service:8084