version: "3.9"
services:
  sqldb:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CAH
      MYSQL_DATABASE: cah
      MYSQL_USER: cah
      MYSQL_PASSWORD: cah
    volumes:
      - .:/var/lib/sql/cah
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CAH
    ports:
      - "27017:27017"
    volumes:
      - .:/var/lib/mongo/uno

  persistence:
    container_name: "persistence-service"
    build:
      context: ./Persistence
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    environment:
      - DATABASE_HOST=sqldb:3306
      - MONGODB_HOST=mongodb:27017
      - MYSQL_USER=root
      - MYSQL_PASSWORD=CAH
    stdin_open: true
    tty: true
    depends_on:
      sqldb:
        condition: service_healthy


#  fileio:
#    container_name: "fileio-service"
#    build:
#      context: Persistence
#      dockerfile: ./Dockerfile
#    ports:
#      - "8084:8084"
#    stdin_open: true
#    tty: true

  cah:
    container_name: "cah-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - persistence
    environment:
      - DISPLAY=host.docker.internal:0
      - PERSISTENCEHTTPSERVER=persistence-service:8084